### ISSUE TITLE
This package must have Assembly Definitions (Editor and Runtime)

### ISSUE THREAD

**Issue by renatopp** [truongnguyentungduy/hierarchy-2#1]
Hi!

First of all, great job with this library, it is really great and useful.

- **Unity Version:** 2019.4
- **Problem:** the lack of assembly definitions make it impossible to build a game with this asset.
- **Solution:** just create and include the assembly the definitions on the Editor and Runtime folders.

I hope to create a PR later today.

**Comment by truongnguyentungduy** [comment]
I'm quite curious about this issue. I have used it in a lot of projects and built on windows, android and ios platforms without any problems. I wonder if I have missed any special cases?
Currently, only HierarchyLocalData.cs (Used to contain custom elements, not appear in the hierarchy) is MonoBehaviour script. Gameobject has it tagged as "EditorOnly" and will be deleted when building the game.

**Comment by renatopp** [comment]
Hi @truongnguyentungduy, I still don't know exactly the particularities of how Unity does its stuff, but, AFAIK, once you use assembly definitions in your project, you have to use it everywhere, including 3rd party packages. 

Once you use asmdefs in your project, the magic folder seems to lose their meaning for building. So, since the Hierarchy2's editor scripts are not contained with a assembly definition, when you build the project they are included in the solution.

**Comment by yasirkula** [comment]
I can't comment about build errors but there are 2 other benefits of adding Assembly Definition Files:

- they are mandatory for UPM support
- they help reduce compilation times of other scripts because Hierarchy 2's scripts won't have to be recompiled with them

If you are interested in UPM support, I'd like to promote the [repository structure I've been using](https://github.com/yasirkula/Unity360ScreenshotCapture) for my packages which has worked well for me with minimal changes.
